server:
  port: 9999
spring:
  servlet:
    multipart:
      enabled: true
      #      最大支持文件大小
      max-file-size: 100MB
      #      最大支持请求大小
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost/edge_node
    username: root
    password: '06240118'
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      aop-patterns: com.atguigu.admin.*  #监控SpringBean
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet:   # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false

      web-stat-filter:  # 监控web
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


      filter:
        stat:    # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false

#  jdbc:
#    template:
#      query-timeout: 10
  mvc:
    hiddenmethod:
      filter:
        enabled: false
    contentnegotiation:
      favor-parameter: true

  kafka:
    bootstrap-servers:
      - 47.95.159.86:9092
    producer:
      topic: "edge-cloud"
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: cloud-edge-0
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#  redis:
#    host: 10.136.17.35
#    port: 6379
#    password: "06240118"

  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
    suffix: .html
    prefix: classpath:/templates/

mybatis:
  # 配 置 扫 描
  mapper-locations: classpath*:**/xml/**.xml
#  config-location: classpath:mybatis/mybatis-config.xml

docker:
  url: "tcp://192.168.0.22:2375"#"unix:///var/run/docker.sock"
  restUrl: "https://192.168.0.22:2375"
  #"tcp://192.168.0.18:2375"
  filepath: /Users/zhangran/Documents/cache/files
#文件存储路径
filepath: /Users/zhangran/Documents/cache/files/

logging:
  file:
    name: /Users/zhangran/Documents/cache/logger.log
  level:
    root: info
